// Generated by CoffeeScript 1.10.0
(function() {
  var Bille, Boulier, Tige, UID, on_total;

  UID = 0;

  Bille = (function() {
    function Bille(weight) {
      this.weight = weight;
      this.id = UID++;
      this.html = function() {
        var w;
        w = this.weight > 1 ? "five" : "one";
        return "<div id='" + this.id + "' class='bille " + w + " off' data-weight=" + this.weight + "></div>";
      };
    }

    return Bille;

  })();

  Tige = (function() {
    function Tige(unit) {
      this.unit = unit;
      this.id = UID++;
      this.html = function() {
        return "<div id='" + this.id + "' class='tige' data-unit='" + this.unit + "'>\n  <div class='billes'>\n    <div class='unaire'>\n        <div class='deactivated'></div>\n        <div class='activated'  ></div>\n    </div>\n    \n    <div class='quinaire'>\n        <div class='activated'  ></div>\n        <div class='deactivated'></div>  \n    </div>\n  </div>\n  <div class=\"tpanel\">\n    <div class='unit'>" + (Math.pow(10, this.unit)) + "</div> \n    <input class='unit' type='radio' name='unity' value='" + this.unit + "' >\n  </div>\n</div>";
      };
    }

    return Tige;

  })();

  Boulier = (function() {
    function Boulier(tiges) {
      this.tiges = tiges != null ? tiges : 10;
      this.id = UID++;
      this.html = function() {
        var $boulier, bille, i, j, k, l, m, o, ref, tige;
        $boulier = $("<div id='#" + this.id + "' class='boulier' data-tiges='" + this.tiges + "'></div>");
        for (i = l = 0, ref = this.tiges - 1; 0 <= ref ? l <= ref : l >= ref; i = 0 <= ref ? ++l : --l) {
          tige = new Tige(i);
          $boulier.append(tige.html());
          for (j = m = 1; m <= 5; j = ++m) {
            bille = new Bille(1);
            $boulier.find("#" + tige.id + " .unaire .deactivated").append(bille.html());
          }
          for (k = o = 1; o <= 2; k = ++o) {
            bille = new Bille(5);
            $boulier.find("#" + tige.id + " .quinaire .deactivated").append(bille.html());
          }
        }
        return $("<div/>").append($boulier).html();
      };
    }

    return Boulier;

  })();

  on_total = function() {
    var max, min, n, ref;
    n = 0;
    $(".one.on, .five.on").each(function() {
      var u, w;
      w = parseFloat($(this).attr("data-weight"));
      u = Math.pow(10, parseInt($(this).closest(".tige").attr("data-unit")));
      return n += w * u;
    });
    ref = [0, 0], min = ref[0], max = ref[1];
    $(".boulier").find(".tige").each(function() {
      var d;
      d = parseInt($(this).attr("data-unit"), 10);
      if (d < min) {
        min = d;
      }
      if (d > max) {
        return max = d;
      }
    });
    return $("#x").html(n.toFixed(Math.abs(min)));
  };

  $(function() {
    $("#toggle_value").on("click", function() {
      return $("#x").toggle();
    });
    $("#toggle_orientation").on("click", function() {
      return $(".boulier").toggleClass("horizontal");
    });
    $("#init").on("click", function() {
      var boulier;
      boulier = new Boulier(10);
      $("#wrapper").empty().append(boulier.html());
      return $("input[name='unity']").first().prop('checked', true);
    });
    $("#init").trigger("click");
    $("body").on("click", "input[name='unity']", function() {
      var tige;
      tige = parseInt("" + ($(this).parent().parent().attr('data-unit')));
      return $(".tige").each(function() {
        var p, v;
        p = tige - parseInt($(this).attr("data-unit"));
        v = Math.pow(10, p);
        $(this).attr("data-unit", p);
        $(this).find(".unit").html(v);
        return on_total();
      });
    });
    return $("body").on("click", ".bille", function() {
      var bille, target, tige_id;
      tige_id = $(this).closest(".tige").attr("id");
      bille = $(this);
      if (bille.hasClass("one")) {
        if (bille.hasClass("off")) {
          target = $("#" + tige_id + " .unaire .activated");
        } else {
          target = $("#" + tige_id + " .unaire .deactivated");
        }
      } else {
        if (bille.hasClass("off")) {
          target = $("#" + tige_id + " .quinaire .activated");
        } else {
          target = $("#" + tige_id + " .quinaire .deactivated");
        }
      }
      target.append($(this).nextAll().andSelf().toggleClass("on off"));
      return on_total();
    });
  });

}).call(this);
