// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var html, i, j, k, l, m, unit;
    for (i = k = 5; k >= -5; i = --k) {
      unit = Math.pow(10, i);
      html = "<div id='" + i + "' class='tige'>\n  <div class='unaire'>\n    <div class='deactivated'></div>\n    <div class='activated'></div>\n  </div>\n  <div class='quinaire'>\n    <div class='activated'></div>\n    <div class='deactivated'></div>\n  </div><div class='unit'>" + unit + "</div>\n</div>";
      $("#boulier").append(html);
      for (j = l = 1; l <= 5; j = ++l) {
        $("#" + i + " .unaire .deactivated").append("<div class='bille one off' data-unit=" + unit + "></div>");
      }
      for (j = m = 1; m <= 2; j = ++m) {
        $("#" + i + " .quinaire .deactivated").append("<div class='bille five off' data-unit=" + unit + "></div>");
      }
    }
    $("#HV").on("click", function() {
      return $("#boulier, .unit, .tige, .unaire, .quinaire, .activated, .deactivated, .bille").toggleClass("horizontal");
    });
    return $("body").on("click", ".bille", function() {
      var bille, n, target, tige_id;
      tige_id = $(this).closest(".tige").attr("id");
      bille = $(this);
      if (bille.hasClass("one")) {
        if (bille.hasClass("off")) {
          console.log("woota#0");
          target = $("#" + tige_id + " .unaire .activated");
        } else {
          console.log("woota#1");
          target = $("#" + tige_id + " .unaire .deactivated");
        }
      } else {
        if (bille.hasClass("off")) {
          console.log("woota#2");
          target = $("#" + tige_id + " .quinaire .activated");
        } else {
          console.log("woota#3");
          target = $("#" + tige_id + " .quinaire .deactivated");
        }
      }
      target.append($(this).nextAll().andSelf().toggleClass("on off"));
      n = 0;
      $(".one.on").each(function() {
        return n += parseFloat($(this).attr("data-unit"));
      });
      $(".five.on").each(function() {
        return n += parseFloat($(this).attr("data-unit")) * 5;
      });
      return $("#nombre").html(n);
    });
  });

}).call(this);
