// Generated by CoffeeScript 1.10.0
(function() {
  var Bille, Boulier, Tige, UID, magnify, on_total;

  UID = 0;

  magnify = function(str) {
    str = str.split('.');
    if (str[0].length >= 5) {
      str[0] = str[0].replace(/(\d)(?=(\d{3})+$)/g, '$1 ');
    }
    if (str[1] && str[1].length >= 5) {
      str[1] = str[1].replace(/(\d{3})/g, '$1 ');
    }
    return str.join('.');
  };

  on_total = function(id) {
    var max, min, n, ref;
    n = 0;
    $("#" + id + " .one.on, .five.on").each(function() {
      var u, w;
      w = parseFloat($(this).attr("data-weight"));
      u = Math.pow(10, parseInt($(this).closest(".tige").attr("data-unit")));
      return n += w * u;
    });
    ref = [0, 0], min = ref[0], max = ref[1];
    $("#" + id).find(".tige").each(function() {
      var d;
      d = parseInt($(this).attr("data-unit"), 10);
      if (d < min) {
        min = d;
      }
      if (d > max) {
        return max = d;
      }
    });
    return $("#" + id + " #x").html(magnify(n.toFixed(Math.abs(min))));
  };

  Bille = (function() {
    function Bille(weight) {
      this.weight = weight;
      this.id = UID++;
      this.html = function() {
        var w;
        w = this.weight > 1 ? "five" : "one";
        return "<div id='" + this.id + "' class='bille " + w + " off' data-weight=" + this.weight + "></div>";
      };
    }

    return Bille;

  })();

  Tige = (function() {
    function Tige(unit) {
      this.unit = unit;
      this.id = UID++;
      this.html = function() {
        return "<div id='" + this.id + "' class='tige' data-unit='" + this.unit + "'>\n  <div class='billes'>\n    <div class='unaire'><div class='deactivated'></div><div class='activated'  ></div></div>  \n    <div class='quinaire'><div class='activated'  ></div><div class='deactivated'></div></div>\n  </div>\n  <div class=\"tpanel\">\n    <input type='radio' name='unity' value='" + this.unit + "' >\n    <div class='unit'> " + (magnify(Math.pow(10, this.unit).toString())) + "</div> \n  </div>\n</div>";
      };
    }

    return Tige;

  })();

  Boulier = (function() {
    function Boulier(tiges1, $container) {
      this.tiges = tiges1 != null ? tiges1 : 10;
      this.id = UID++;
      this.html = function() {
        var $boulier, bille, i, j, k, l, m, o, ref, tige;
        $boulier = $("<div id='" + this.id + "' class='boulier' data-tiges='" + this.tiges + "'>\n  <div id='panel'>\n    <input type='range'  min='1' max='20' value='" + this.tiges + "' name='tselect' class='tselect'/>\n    <button class='init' data-id='" + this.id + "'>&#10026;</button>\n    <button class='toggle_orientation'    data-id='" + this.id + "'>&#8635; </button>\n    <button class='toggle_value'          data-id='" + this.id + "'>&#9746; </button>\n    <span id=\"x\">0</span>\n</div></div>");
        for (i = l = 0, ref = this.tiges - 1; 0 <= ref ? l <= ref : l >= ref; i = 0 <= ref ? ++l : --l) {
          tige = new Tige(i);
          $boulier.append(tige.html());
          for (j = m = 1; m <= 5; j = ++m) {
            bille = new Bille(1);
            $boulier.find("#" + tige.id + " .unaire .deactivated").append(bille.html());
          }
          for (k = o = 1; o <= 2; k = ++o) {
            bille = new Bille(5);
            $boulier.find("#" + tige.id + " .quinaire .deactivated").append(bille.html());
          }
        }
        return $("<div/>").append($boulier).html();
      };
      if ($container.length) {
        $container.empty().append(this.html());
        $("input[name='unity']").first().prop('checked', true);
      }
    }

    return Boulier;

  })();

  $(function() {
    $("body").on("click", ".init", function() {
      var boulier, id, tiges;
      id = $(this).attr("data-id");
      tiges = parseInt($("#" + id).find(".tige").length);
      return boulier = new Boulier(tiges, $("#wrappers"));
    });
    $("body").on("click", ".toggle_value", function() {
      var id;
      id = $(this).attr("data-id");
      return $("#" + id + " #x").toggle();
    });
    $("body").on("click", ".toggle_orientation", function() {
      var id;
      id = $(this).attr("data-id");
      return $("#" + id).toggleClass("horizontal");
    });
    $("body").on("click", "input[name='unity']", function() {
      var id, tige;
      id = $(this).closest(".boulier").attr("id");
      tige = parseInt("" + ($(this).parent().parent().attr('data-unit')));
      return $("#" + id + " .tige").each(function() {
        var p, v;
        p = tige - parseInt($(this).attr("data-unit"));
        v = Math.pow(10, p);
        $(this).attr("data-unit", p);
        $(this).find(".unit").html(magnify(v.toString()));
        return on_total(id);
      });
    });
    $("body").on("click", ".bille", function() {
      var bille, boulier_id, target, tige_id;
      boulier_id = $(this).closest(".boulier").attr("id");
      tige_id = $(this).closest(".tige").attr("id");
      bille = $(this);
      if (bille.hasClass("one")) {
        if (bille.hasClass("off")) {
          target = $("#" + tige_id + " .unaire .activated");
        } else {
          target = $("#" + tige_id + " .unaire .deactivated");
        }
      } else {
        if (bille.hasClass("off")) {
          target = $("#" + tige_id + " .quinaire .activated");
        } else {
          target = $("#" + tige_id + " .quinaire .deactivated");
        }
      }
      target.append($(this).nextAll().andSelf().toggleClass("on off"));
      return on_total(boulier_id);
    });
    $("body").on("change", ".tselect", function() {
      var id, v;
      v = $(this).val();
      id = $(this).closest(".boulier").attr("id");
      return new Boulier(parseInt(v), $("#wrappers"));
    });
    return new Boulier(5, $("#wrappers"));
  });

}).call(this);
